//
// Created by amaury on 05/02/18.
//

#ifndef JEU2D_MODELCONSTANTS_H
#define JEU2D_MODELCONSTANTS_H

#define STD_SIZE 16
#define BLOCK_SIZE STD_SIZE
#define ENTITY_SIZE 16
#define ENTITY_WIDTH STD_SIZE
#define ENTITY_HEIGHT (STD_SIZE + (STD_SIZE / 2))



#endif //JEU2D_MODELCONSTANTS_H
